import localFont from "next/font/local";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "@/components/Provider";
import "./globals.css";

const Radiant = localFont({
  src: [
    {
      path: "./fonts/OPTIRadiant-Medium.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/OPTIRadiant-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/OPTIRadiant-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/OPTIRadiant-Heavy.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-radiant",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
